image: Visual Studio 2017

platform: x64

configuration:
  - Release

environment:
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2017_64
      BUILD: qbs
    - QTDIR: C:\Qt\5.12\msvc2017_64
      BUILD: qbs
    - QTDIR: C:\Qt\5.12\msvc2017_64
      BUILD: qmake

for:
- matrix:
    only:
      - BUILD: qmake
  before_build:
    - set PATH=%QTDIR%\bin;%PATH%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
    - qmake -r
  build_script:
    - nmake
  test_script:
    - nmake check

- matrix:
    only:
      - BUILD: qbs
  install:
    - cinst qbs
  before_build:
    - set PATH=%QTDIR%\bin;%PATH%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - qbs config --list profiles
  build_script:
    - qbs build --file verdigris.qbs --build-directory %TMP%\build
  test_script:
    - qbs build --file verdigris.qbs --build-directory %TMP%\build -p autotest-runner
