name: Macos

on:
  push

env:
  BUILD_TYPE: Release
  MIN_OSX_VERSION: 11.0

jobs:
  build_release:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - run: brew install ninja qt
    - run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: >
        cmake .. -GNinja
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DSERVER=OFF
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${{env.MIN_OSX_VERSION}}
        -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

    - name: Build
      run: cmake --build build --target viage

    - uses: actions/upload-artifact@v3
      with:
        name: viage
        path: ${{github.workspace}}/build/bin/viage.dmg
