name: Windows

on:
  push

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.2
  IFW_VERSION: 4.7

jobs:
  build_release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: seanmiddleditch/gha-setup-ninja@v4

    - uses: jurplel/install-qt-action@v3
      with:
       version: ${{env.QT_VERSION}}
       host: 'windows'
       target: 'desktop'
       arch: 'win64_mingw'
       modules: 'qtmultimedia'
       tools: 'tools_ifw tools_mingw90,qt.tools.win64_mingw900'
       dir: ${{github.workspace}}

    - run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: >
        cmake .. -GNinja
        -DCMAKE_CXX_COMPILER=D:/a/viage/viage/Qt/Tools/mingw1120_64/bin/g++.exe
        -DCMAKE_C_COMPILER=D:/a/viage/viage/Qt/Tools/mingw1120_64/bin/gcc.exe
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DSERVER=OFF
        -DCPACK_IFW_ROOT=${{github.workspace}}/Qt/Tools/QtInstallerFramework/${{env.IFW_VERSION}}

    - name: Build
      run: cmake --build build --target package

    - uses: actions/upload-artifact@v4
      with:
        name: viage
        path: ${{github.workspace}}/build/viage-*-win64.exe
