name: Windows

on:
  push
#  push:
#    tags:
#      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 6.3.2

jobs:
  build_release:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: seanmiddleditch/gha-setup-ninja@v3
    - run: pip install aqtinstall conan
    - run: aqt install-qt windows desktop ${{env.QT_VERSION}} win64_mingw -m qtmultimedia
    - run: aqt install-tool windows desktop tools_ifw

    - run: mkdir build

    - name: install connan packages
      working-directory: ./build
      run: >
        conan install ..
        -s compiler="Visual Studio"
        -s compiler.version=16
        -sbuild_type=${{env.BUILD_TYPE}}
        -g cmake_paths

    - name: Configure CMake
      working-directory: ./build
      run: >
        cmake .. -GNinja
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DSERVER=OFF
        -DCMAKE_TOOLCHAIN_FILE="conan_paths.cmake"
        -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.QT_VERSION}}/mingw_64
        -DCPACK_IFW_ROOT='${{github.workspace}}/Tools/QtInstallerFramework/4.4'
#      run: cmake -GNinja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSERVER=OFF -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.QT_VERSION}}/mingw_64 -DCPACK_IFW_ROOT=${{github.workspace}}/Tools/QtInstallerFramework/4.4

    - name: Build
      working-directory: ./build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package

    - uses: actions/upload-artifact@v3
      with:
        name: viage
        path: ${{github.workspace}}/build/client/viage-*-win64.exe

    #- name: Test
      # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # run: ctest -C ${{env.BUILD_TYPE}}
